=== FTWinston/Chessmaker/ChessMaker/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="viewBox">
		<xs:restriction base="xs:string">
			<xs:pattern value="-?(\d*\.)?\d+ -?(\d*\.)?\d+ -?(\d*\.)?\d+ -?(\d*\.)?\d+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="svgPath">
		<xs:restriction base="xs:string">
			<xs:pattern value="M-?(\d*\.)?\d+ -?(\d*\.)?\d+ .*Z" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="boardColor">
		<xs:restriction base="xs:string">
			<xs:enumeration value="light" />
			<xs:enumeration value="mid" />
			<xs:enumeration value="dark" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="notation">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"/>
			<xs:maxLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

  <xs:simpleType name="numericComparison">
    <xs:restriction base="xs:string">
      <xs:enumeration value="equals" />
      <xs:enumeration value="less than" />
      <xs:enumeration value="greater than" />
      <xs:enumeration value="less than or equals" />
      <xs:enumeration value="greater than or equals" />
    </xs:restriction>
  </xs:simpleType>
  
	<xs:complexType name="conditions">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="and" type="conditions"/>
			<xs:element name="or" type="conditions"/>
			<xs:element name="not" type="conditions"/>
			<xs:element name="nand" type="conditions"/>
			<xs:element name="nor" type="conditions"/>
			<xs:element name="xor" type="conditions"/>

			<xs:element name="type">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="of" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>

			<xs:element name="owner">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="owner">
							<xs:attribute name="of" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>

      <xs:element name="moveNumber">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
              <xs:attribute name="of" type="xs:string"/>
              <xs:attribute name="comparison" type="numericComparison"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

      <xs:element name="maxDist">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
              <xs:attribute name="dir" type="direction" use="required"/>
              <xs:attribute name="comparison" type="numericComparison"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

      <xs:element name="turnsSinceLastMove">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
              <xs:attribute name="of" type="xs:string"/>
              <xs:attribute name="comparison" type="numericComparison"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

			<!--
      <xs:element name="threatened">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:boolean">
              <xs:attribute name="where" type="partOfMove" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

      <xs:element name="compare">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="comparison_value">
              <xs:attribute name="var" type="comparison_property"/>
              <xs:attribute name="comparison" type="numeric_comparison_type"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

      <xs:element name="num_pieces_in_range">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="comparison_value">
              <xs:attribute name="type" type="xs:string" use="required"/>
              <xs:attribute name="owner" type="owner" use="required"/>
              <xs:attribute name="rank_min" type="comparison_value" use="required"/>
              <xs:attribute name="rank_max" type="comparison_value" use="required"/>
              <xs:attribute name="col_min" type="comparison_value" use="required"/>
              <xs:attribute name="col_max" type="comparison_value" use="required"/>
              <xs:attribute name="comparison" type="numeric_comparison_type" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

      <xs:element name="move_causes_check" type="xs:boolean"/>
      <xs:element name="move_causes_checkmate" type="xs:boolean"/>
	  
	  
      <xs:element name="checkmate">
        <xs:complexType>
          <xs:attribute name="num" type="piece_count" default="any"/>
          <xs:attribute name="type" type="xs:string" default="any"/>
          <xs:attribute name="owner" type="owner" default="any"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="pieces_threatened">
        <xs:complexType>
          <xs:attribute name="num" type="piece_count" default="any"/>
          <xs:attribute name="type" type="xs:string" default="any"/>
          <xs:attribute name="owner" type="owner" default="any"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="repeated_check">
        <xs:complexType>
          <xs:attribute name="duration" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="type" type="xs:string" default="any"/>
          <xs:attribute name="owner" type="owner" default="any"/>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="no_moves_possible">
        <xs:complexType>
          <xs:attribute name="type" type="xs:string" default="any"/>
          <xs:attribute name="player" type="owner" default="any"/>
        </xs:complexType>
      </xs:element>

      <xs:element name="repetition_of_position">
        <xs:complexType>
      <xs:attribute name="occurances" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="turns_since_last_capture">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:nonNegativeInteger">
          <xs:attribute name="type" type="xs:string" use="required"/>
          <xs:attribute name="owner" type="owner" use="required"/>
          <xs:attribute name="comparison" type="numeric_comparison_type" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="turns_since_last_move">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:nonNegativeInteger">
          <xs:attribute name="type" type="xs:string" use="required"/>
          <xs:attribute name="owner" type="owner" use="required"/>
          <xs:attribute name="comparison" type="numeric_comparison_type" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  -->
		</xs:choice>
	</xs:complexType>

	<xs:simpleType name="when">
		<xs:restriction base="xs:string">
			<xs:enumeration value="any" />
			<xs:enumeration value="capture" />
			<xs:enumeration value="move" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="owner">
		<xs:restriction base="xs:string">
			<xs:enumeration value="any" />
			<xs:enumeration value="self" />
			<xs:enumeration value="enemy" />
			<xs:enumeration value="ally" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="direction">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="distance">
		<xs:restriction base="xs:string">
			<xs:pattern value="any|(((max|prev)(\+|-))?[1-9][0-9]*)"/>
			<!-- a positive integer, the text "any", or "max" or "prev" +- a positive integer -->
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="distanceIncZero">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]+|any|max"/>
			<!-- a non-negative integer, or the text "any" or "max" -->
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="repeatCount">
		<xs:restriction base="xs:string">
			<xs:pattern value="[1-9][0-9]*|unbounded"/>
			<!-- a positive integer, or the text "unbounded" -->
		</xs:restriction>
	</xs:simpleType>


	<xs:complexType name="slide">
		<xs:sequence>
			<xs:element name="conditions" type="conditions" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="piece" type="xs:string" default="self"/>
		<xs:attribute name="dir" type="direction" use="required"/>
		<xs:attribute name="dist" type="distance" use="required"/>
		<xs:attribute name="distMax" type="distance"/>
		<!-- if present, limits the movement to between dist & distLimit -->
		<xs:attribute name="when" type="when" default="any"/>
	</xs:complexType>

	<xs:complexType name="leap">
		<xs:sequence>
			<xs:element name="conditions" type="conditions" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="piece" type="xs:string" default="self"/>
		<xs:attribute name="dir" type="direction" use="required"/>
		<xs:attribute name="dist" type="distance" use="required"/>
		<xs:attribute name="distMax" type="distance"/>
		<xs:attribute name="secondDir" type="direction"/>
		<xs:attribute name="secondDist" type="distanceIncZero" default="0"/>
		<xs:attribute name="when" type="when" default="any"/>
	</xs:complexType>

	<xs:complexType name="hop">
		<xs:sequence>
			<xs:element name="conditions" type="conditions" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="piece" type="xs:string" default="self"/>
		<xs:attribute name="dir" type="direction" use="required"/>
		<xs:attribute name="distToHurdle" type="distance" use="required"/>
		<xs:attribute name="distToHurdleMax" type="distance"/>
		<xs:attribute name="distAfterHurdle" type="distance" use="required"/>
		<xs:attribute name="distAfterHurdleMax" type="distance"/>
		<xs:attribute name="when" type="when" default="any"/>
		<xs:attribute name="captureHurdle" type="xs:boolean" default="false"/>
	</xs:complexType>

	<xs:complexType name="shoot">
		<xs:sequence>
			<xs:element name="conditions" type="conditions" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="piece" type="xs:string" default="self"/>
		<xs:attribute name="dir" type="direction" use="required"/>
		<xs:attribute name="dist" type="distance" use="required"/>
		<xs:attribute name="distMax" type="distance"/>
		<!-- if present, limits the movement to between dist & distLimit -->
		<xs:attribute name="secondDir" type="direction"/>
		<xs:attribute name="secondDist" type="distanceIncZero" default="0"/>
	</xs:complexType>

	<xs:complexType name="moveLike">
		<xs:sequence>
			<xs:element name="conditions" type="conditions" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="other" type="xs:string" use="required"/>
		<xs:attribute name="when" type="when" default="any"/>
	</xs:complexType>

	<xs:complexType name="referencePiece">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="dir" type="direction"/>
		<xs:attribute name="dist" type="distance"/>
		<xs:attribute name="type" type="xs:string" default="any"/>
		<xs:attribute name="owner" type="owner" default="any"/>
	</xs:complexType>

	<xs:complexType name="moveList">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="slide" type="slide"/>
				<xs:element name="leap" type="leap"/>
				<xs:element name="hop" type="hop"/>
				<xs:element name="shoot" type="shoot"/>
				<xs:element name="moveLike" type="moveLike"/>
				<xs:element name="sequence" type="moveSequence"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="moveSequence">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="slide" type="slide"/>
			<xs:element name="leap" type="leap"/>
			<xs:element name="hop" type="hop"/>
			<xs:element name="shoot" type="shoot"/>
			<xs:element name="moveLike" type="moveLike"/>
			<xs:element name="repeat" type="moveSequenceLoop"/>
			<xs:element name="whenPossible" type="moveSequence"/>
			<xs:element name="referencePiece" type="referencePiece"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="moveSequenceLoop">
		<xs:complexContent>
			<xs:extension base="moveSequence">
				<xs:attribute name="min" type="xs:nonNegativeInteger" use="required"/>
				<xs:attribute name="max" type="repeatCount" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="game">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="board">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="cell">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="link" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="dir" type="xs:string" use="required"/>
												<xs:attribute name="to" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:string" use="required"/>
									<xs:attribute name="fill" type="boardColor" use="required"/>
									<xs:attribute name="border" type="boardColor" use="optional"/>
									<xs:attribute name="path" type="svgPath" use="required"/>
								</xs:complexType>
							</xs:element>

							<xs:element name="line">
								<xs:complexType>
									<xs:attribute name="color" type="boardColor" use="required"/>
									<xs:attribute name="x1" type="xs:decimal" use="required"/>
									<xs:attribute name="y1" type="xs:decimal" use="required"/>
									<xs:attribute name="x2" type="xs:decimal" use="required"/>
									<xs:attribute name="y2" type="xs:decimal" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="viewBox" type="viewBox" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="dirs">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="relative" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="link" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="from" type="xs:string" use="required"/>
												<xs:attribute name="to" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="group" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="include" minOccurs="2" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="dir" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="pieces">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="piece" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="appearance" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded" />
												</xs:sequence>
												<xs:attribute name="player" type="xs:string" />
												<xs:attribute name="transform" type="xs:string" />
											</xs:complexType>
										</xs:element>
										<xs:element name="moves" type="moveList" minOccurs="1" maxOccurs="1"/>
										<!--
										<xs:element name="special" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:choice minOccurs="0" maxOccurs="1">
														<xs:element name="royal"/>
														<xs:element name="anti_royal"/>
													</xs:choice>
													<xs:choice minOccurs="0" maxOccurs="unbounded">
														<xs:element name="immobilize">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="conditions" type="conditions" minOccurs="0" maxOccurs="1"/>
																</xs:sequence>
																<xs:attribute name="dir" type="direction" use="required"/>
																<xs:attribute name="dist" type="distance" use="required"/>
																<xs:attribute name="dist2" type="distance"/>
																<xs:attribute name="offset" type="xs:nonNegativeInteger" default="0"/>
																<xs:attribute name="allow_immobilized_suicide" type="xs:boolean" default="false"/>
															</xs:complexType>
														</xs:element>
													</xs:choice>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="promotion" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="conditions" type="conditions" minOccurs="0" maxOccurs="1"/>
													<xs:element name="option" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
												</xs:sequence>
												<xs:attribute name="mandatory" type="xs:boolean" default="true"/>
												<xs:attribute name="type" type="promotionType" use="required"/>
											</xs:complexType>
										</xs:element>
										-->
										<xs:element name="capturedAs" type="xs:string" minOccurs="0" maxOccurs="1"/>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string"/>
									<xs:attribute name="value" type="xs:nonNegativeInteger"/>
									<xs:attribute name="notation" type="notation"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="setup">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="player" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="piece" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="location" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="forwardDirection" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FTWinston/Chessmaker/ChessMaker/test.xml
<game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<board viewBox="20 20 360 360">
		<cell id="cell63" color="dark" path="M300 340 m-20 -20 l41 0 l0 40 l-41 0 Z">
			<link dir="west" to="cell62" />
			<link dir="east" to="cell64" />
			<link dir="north" to="cell55" />
			<link dir="northwest" to="cell54" />
			<link dir="northeast" to="cell56" />
		</cell>
		<cell id="cell64" color="light" path="M340 340 m-20 -20 l40 0 l0 40 l-40 0 Z">
			<link dir="west" to="cell63" />
			<link dir="north" to="cell56" />
			<link dir="northwest" to="cell55" />
		</cell>
		<line color="mid" x1="40" y1="360" x2="360" y2="40" />
	</board>
	<dirs>
		<relative name="left90">
			<link from="north" to="west" />
			<link from="west" to="south" />
			<link from="south" to="east" />
			<link from="east" to="north" />
		</relative>
		<relative name="right90">
			<link from="north" to="east" />
			<link from="west" to="north" />
			<link from="south" to="west" />
			<link from="east" to="south" />
		</relative>
		<group name="orthogonal">
			<include name="north" />
			<include name="south" />
			<include name="east" />
			<include name="west" />
		</group>
		<group name="diagonal">
			<include name="northeast" />
			<include name="northwest" />
			<include name="southeast" />
			<include name="southwest" />
		</group>
		<group name="sideways">
			<include name="east" />
			<include name="west" />
		</group>
	</dirs>
	<pieces>
		<piece name="king">
			<appearance player="white" width="45" height="45">
				<g style="fill:none; fill-opacity:1; fill-rule:evenodd; stroke:#000000; stroke-width:1.5; stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4; stroke-dasharray:none; stroke-opacity:1;">
					<path d="M 22.5,11.63 L 22.5,6" style="fill:none; stroke:#000000; stroke-linejoin:miter;" />
					<path d="M 20,8 L 25,8" style="fill:none; stroke:#000000; stroke-linejoin:miter;" />
					<path d="M 22.5,25 C 22.5,25 27,17.5 25.5,14.5 C 25.5,14.5 24.5,12 22.5,12 C 20.5,12 19.5,14.5 19.5,14.5 C 18,17.5 22.5,25 22.5,25" style="fill:#ffffff; stroke:#000000; stroke-linecap:butt; stroke-linejoin:miter;" />
					<path d="M 11.5,37 C 17,40.5 27,40.5 32.5,37 L 32.5,30 C 32.5,30 41.5,25.5 38.5,19.5 C 34.5,13 25,16 22.5,23.5 L 22.5,27 L 22.5,23.5 C 19,16 9.5,13 6.5,19.5 C 3.5,25.5 11.5,29.5 11.5,29.5 L 11.5,37 z " style="fill:#ffffff; stroke:#000000;" />
					<path d="M 11.5,30 C 17,27 27,27 32.5,30" style="fill:none; stroke:#000000;" />
					<path d="M 11.5,33.5 C 17,30.5 27,30.5 32.5,33.5" style="fill:none; stroke:#000000;" />
					<path d="M 11.5,37 C 17,34 27,34 32.5,37" style="fill:none; stroke:#000000;" />
				</g>
			</appearance>
			<appearance player="black" width="45" height="45">
				<g style="fill:none; fill-opacity:1; fill-rule:evenodd; stroke:#000000; stroke-width:1.5; stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4; stroke-dasharray:none; stroke-opacity:1;">
					<path d="M 22.5,11.63 L 22.5,6" style="fill:none; stroke:#000000; stroke-linejoin:miter;" id="path6570" />
					<path d="M 22.5,25 C 22.5,25 27,17.5 25.5,14.5 C 25.5,14.5 24.5,12 22.5,12 C 20.5,12 19.5,14.5 19.5,14.5 C 18,17.5 22.5,25 22.5,25" style="fill:#000000;fill-opacity:1; stroke-linecap:butt; stroke-linejoin:miter;" />
					<path d="M 11.5,37 C 17,40.5 27,40.5 32.5,37 L 32.5,30 C 32.5,30 41.5,25.5 38.5,19.5 C 34.5,13 25,16 22.5,23.5 L 22.5,27 L 22.5,23.5 C 19,16 9.5,13 6.5,19.5 C 3.5,25.5 11.5,29.5 11.5,29.5 L 11.5,37 z " style="fill:#000000; stroke:#000000;" />
					<path d="M 20,8 L 25,8" style="fill:none; stroke:#000000; stroke-linejoin:miter;" />
					<path d="M 32,29.5 C 32,29.5 40.5,25.5 38.03,19.85 C 34.15,14 25,18 22.5,24.5 L 22.51,26.6 L 22.5,24.5 C 20,18 9.906,14 6.997,19.85 C 4.5,25.5 11.85,28.85 11.85,28.85" style="fill:none; stroke:#ffffff;" />
					<path d="M 11.5,30 C 17,27 27,27 32.5,30 M 11.5,33.5 C 17,30.5 27,30.5 32.5,33.5 M 11.5,37 C 17,34 27,34 32.5,37" style="fill:none; stroke:#ffffff;" />
				</g>
			</appearance>
			<moves>
				<slide dist="1" dir="any" />
			</moves>
		</piece>
		<piece name="queen">
			<appearance player="white" width="45" height="45">
				<g style="opacity:1; fill:#ffffff; fill-opacity:1; fill-rule:evenodd; stroke:#000000; stroke-width:1.5; stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4; stroke-dasharray:none; stroke-opacity:1;">
					<path d="M 9 13 A 2 2 0 1 1  5,13 A 2 2 0 1 1  9 13 z" transform="translate(-1,-1)" />
					<path d="M 9 13 A 2 2 0 1 1  5,13 A 2 2 0 1 1  9 13 z" transform="translate(15.5,-5.5)" />
					<path d="M 9 13 A 2 2 0 1 1  5,13 A 2 2 0 1 1  9 13 z" transform="translate(32,-1)" />
					<path d="M 9 13 A 2 2 0 1 1  5,13 A 2 2 0 1 1  9 13 z" transform="translate(7,-4.5)" />
					<path d="M 9 13 A 2 2 0 1 1  5,13 A 2 2 0 1 1  9 13 z" transform="translate(24,-4)" />
					<path d="M 9,26 C 17.5,24.5 30,24.5 36,26 L 38,14 L 31,25 L 31,11 L 25.5,24.5 L 22.5,9.5 L 19.5,24.5 L 14,10.5 L 14,25 L 7,14 L 9,26 z " style="stroke-linecap:butt;" />
					<path d="M 9,26 C 9,28 10.5,28 11.5,30 C 12.5,31.5 12.5,31 12,33.5 C 10.5,34.5 10.5,36 10.5,36 C 9,37.5 11,38.5 11,38.5 C 17.5,39.5 27.5,39.5 34,38.5 C 34,38.5 35.5,37.5 34,36 C 34,36 34.5,34.5 33,33.5 C 32.5,31 32.5,31.5 33.5,30 C 34.5,28 36,28 36,26 C 27.5,24.5 17.5,24.5 9,26 z " style="stroke-linecap:butt;" />
					<path d="M 11.5,30 C 15,29 30,29 33.5,30" style="fill:none;" />
					<path d="M 12,33.5 C 18,32.5 27,32.5 33,33.5" style="fill:none;" />
				</g>
			</appearance>
			<appearance player="black" width="45" height="45">
				<g style="opacity:1; fill:000000; fill-opacity:1; fill-rule:evenodd; stroke:#000000; stroke-width:1.5; stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4; stroke-dasharray:none; stroke-opacity:1;">
					<g style="fill:#000000; stroke:none;">
						<circle cx="6" cy="12" r="2.75" />
						<circle cx="14" cy="9" r="2.75" />
						<circle cx="22.5" cy="8" r="2.75" />
						<circle cx="31" cy="9" r="2.75" />
						<circle cx="39" cy="12" r="2.75" />
					</g>
					<path d="M 9,26 C 17.5,24.5 30,24.5 36,26 L 38.5,13.5 L 31,25 L 30.7,10.9 L 25.5,24.5 L 22.5,10 L 19.5,24.5 L 14.3,10.9 L 14,25 L 6.5,13.5 L 9,26 z" style="stroke-linecap:butt; stroke:#000000;" />
					<path d="M 9,26 C 9,28 10.5,28 11.5,30 C 12.5,31.5 12.5,31 12,33.5 C 10.5,34.5 10.5,36 10.5,36 C 9,37.5 11,38.5 11,38.5 C 17.5,39.5 27.5,39.5 34,38.5 C 34,38.5 35.5,37.5 34,36 C 34,36 34.5,34.5 33,33.5 C 32.5,31 32.5,31.5 33.5,30 C 34.5,28 36,28 36,26 C 27.5,24.5 17.5,24.5 9,26 z" style="stroke-linecap:butt;" />
					<path d="M 11,38.5 A 35,35 1 0 0 34,38.5" style="fill:none; stroke:#000000; stroke-linecap:butt;" />
					<path d="M 11,29 A 35,35 1 0 1 34,29" style="fill:none; stroke:#ffffff;" />
					<path d="M 12.5,31.5 L 32.5,31.5" style="fill:none; stroke:#ffffff;" />
					<path d="M 11.5,34.5 A 35,35 1 0 0 33.5,34.5" style="fill:none; stroke:#ffffff;" />
					<path d="M 10.5,37.5 A 35,35 1 0 0 34.5,37.5" style="fill:none; stroke:#ffffff;" />
				</g>
			</appearance>
			<moves>
				<slide dist="any" dir="any" />
			</moves>
		</piece>
	</pieces>
	<setup>
		<player name="white" forwardDirection="north">
			<piece type="knight" location="A8"/>
			<piece type="fish" location="A7"/>
			<piece type="joker" location="held"/>
		</player>
		<player name="black" forwardDirection="south">
			<piece type="knight" location="A1"/>
			<piece type="fish" location="A2"/>
			<piece type="joker" location="held"/>
		</player>
	</setup>
</game>
